% ============================================================================ %
\NeedsTeXFormat{LaTeX2e}%
\ProvidesClass{resumex}[%
    2018/05/27 - %
    Resume and Curriculum Vitae Builder %
    v1.0 - %
    LaTeX Custom Package %
    by Elan H. Herrera%
]%
% ============================================================================ %
\ProcessOptions\relax%
% ============================================================================ %
\LoadClass[oneside]{article}%
% ============================================================================ %
\RequirePackage{resumex}% underlying project tools package for large document
% ============================================================================ %